name: whatsapp_server
description: whatsapp managing server
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  dart_verse_backend: ^1.4.0
  whatsapp_shared_code: 
    path: ../whatsapp_shared_code
  json_annotation: ^4.8.1



dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  json_serializable: ^6.7.1
  copy_with_extension_gen: ^4.0.0
